name: maven-build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
    steps:
      - uses: kamiazya/setup-graphviz@v1
      - uses: actions/checkout@v2
      - name: setup-jdk-${{ matrix.java }}
        uses: actions/setup-java@v3.4.1
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: build-jar
        run: mvn -B install
